name: recyleto_app
description: A comprehensive pharmacy management mobile application
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http: ^1.1.0
  intl: ^0.20.2
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.2.1
  permission_handler: ^11.0.1
  flutter_local_notifications: ^17.2.1
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  flutter_slidable: ^3.0.1
  flutter_datetime_picker_plus: ^2.1.0
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.1.2
  dio: ^5.4.0
  http_parser: ^4.0.2
  socket_io_client: ^2.0.3+1

  # Payment Gateway Libraries
  stripe_platform_interface: ^10.2.0
  flutter_stripe: ^10.2.0
  pay: ^2.0.0
  razorpay_flutter: ^1.3.5
  flutterwave_standard: ^1.0.7
  webview_flutter: ^4.4.2
  flutter_gen: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  generate: true
